apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- frontend-deployment.yaml
- services.yaml
# These are the placeholders we will target
images:
- name: <BACKEND_IMAGE_PLACEHOLDER>
  newName: my-backend-image
  newTag: latest
- name: <FRONTEND_IMAGE_PLACEHOLDER>
  newName: my-frontend-image
  newTag: latest
